seed: 12345
mode: "dataset"
output_path: "/home/amine/Documents/Research/gaussian-splatting-playground/data/runs"

dataset_config:
  dataset: "tum_rgbd"
  dataset_path: "/home/amine/Documents/Research/gaussian-splatting-playground/data/TUM_RGBD-SLAM/rgbd_dataset_freiburg3_long_office_household"
  frame_limit: -1
  H: 480
  W: 640
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 50
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]
  depth_scale: 5000.0

mapping:
  submap_creation_criteria: 
    criterion: "motion_threshold"
    translation_threshold: 0.5 # meters
    rotation_threshold: 50 # degrees

mapper:
  new_submap_every: 50
  map_every: 5
  iterations: 100
  new_submap_iterations: 200
  new_submap_points_num: 100000 
  new_submap_gradient_points_num: 50000 
  new_frame_sample_size: 30000
  new_points_radius: 0.0001
  current_view_weight: 0.4 # What portion of iterations to spend on the current view
  alpha_threshold: 0.6
  pruning_threshold: 0.5 


# project_name: "Gaussian_SLAM_scannet"
# dataset_name: "scan_net"
# checkpoint_path: null
# use_wandb: False
# frame_limit: -1 # for debugging, set to -1 to disable
# seed: 0
# mapping:
#   new_submap_every: 50
#   map_every: 1
#   iterations: 100
#   new_submap_iterations: 100
#   new_submap_points_num: 100000 
#   new_submap_gradient_points_num: 50000 
#   new_frame_sample_size: 30000 
#   new_points_radius: 0.0001
#   current_view_opt_iterations: 0.4 # What portion of iterations to spend on the current view
#   alpha_thre: 0.6
#   pruning_thre: 0.5
#   submap_using_motion_heuristic: False
# tracking:
#   gt_camera: False
#   w_color_loss: 0.6
#   iterations: 200
#   cam_rot_lr: 0.002
#   cam_trans_lr: 0.01
#   odometry_type: "const_speed"  # gt, const_speed, odometer
#   help_camera_initialization: False # temp option to help const_init
#   init_err_ratio: 5
#   odometer_method: "hybrid" # hybrid or point_to_plane
#   filter_alpha: True
#   filter_outlier_depth: True
#   alpha_thre: 0.98
#   soft_alpha: True
#   mask_invalid_depth: True
# cam: 
#   H: 480 
#   W: 640
#   fx: 577.590698
#   fy: 578.729797
#   cx: 318.905426
#   cy: 242.683609
#   depth_scale: 1000.
#   crop_edge: 12